version: 2

references:
  container_config: &container_config
    working_directory: ~/project
    docker:
      - image: alpine

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run: echo $HOGE
      - run: echo $FUGA
      - run: echo $PIYO
