version: 2

jobs:
  echo1:
    working_directory: ~/project
    docker:
      - image: alpine
    steps:
      - checkout
      - run: echo $HOGE

  echo2:
    working_directory: ~/project
    docker:
      - image: alpine
    steps:
      - checkout
      - run: echo $FUGA

  echo3:
    working_directory: ~/project
    docker:
      - image: alpine
    steps:
      - checkout
      - run: echo $PIYO

workflows:
  version: 2
  echo:
    jobs:
      - echo1
      - echo2:
          requires:
            - echo1
          filters:
            branches:
              only: master
      - echo3:
          requires:
            - echo2
