version: 2

references:
  container_config: &container_config
    working_directory: ~/project
    docker:
      - image: alpine

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run: echo build

  echo1:
    <<: *container_config
    steps:
      - checkout
      - run: echo $HOGE

  echo2:
    <<: *container_config
    steps:
      - checkout
      - run: echo $FUGA

  echo3:
    <<: *container_config
    steps:
      - checkout
      - run: echo $PIYO

workflows:
  version: 2
  echo:
    jobs:
      - build
      - echo1
      - echo2:
          requires:
            - echo1
          filters:
            branches:
              only: master
      - echo3:
          requires:
            - echo2
